name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 my-python-app

    - name: Test the application
      run: |
        sleep 10  # Wait for the container to start
        curl -f http://localhost:8080

    - name: Stop Docker container
      run: docker ps -q --filter "ancestor=my-python-app" | xargs -r docker stop