stages:
  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
    - src/mlProject/components/data_validation.py
    - src/mlProject/config/configuration.py
    - src/mlProject/constants/__init__.py
    - src/mlProject/entity/config_entity.py
    - src/mlProject/pipeline/stage_02_data_validation.py
    - src/mlProject/utils/common.py
    outs:
    - artifacts/data_validation/status.txt
  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
    - src/mlProject/components/data_transformation.py
    - src/mlProject/config/configuration.py
    - src/mlProject/constants/__init__.py
    - src/mlProject/entity/config_entity.py
    - src/mlProject/pipeline/stage_03_data_transformation.py
    - src/mlProject/utils/common.py
    outs:
    - artifacts/data_transformation/test.csv
    - artifacts/data_transformation/train.csv
  model_trainer:
    cmd: python src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
    - src/mlProject/components/model_trainer.py
    - src/mlProject/config/configuration.py
    - src/mlProject/constants/__init__.py
    - src/mlProject/entity/config_entity.py
    - src/mlProject/pipeline/stage_04_model_trainer.py
    - src/mlProject/utils/common.py
    params:
    - config/config.yaml:
      - model_trainer
    outs:
    - artifacts/model_trainer/model.joblib
