stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
    - src/mlProject/pipeline/stage_01_data_ingestion.py
    - src/mlProject/components/data_ingestion.py
    - src/mlProject/config/configuration.py
    - src/mlProject/entity/config_entity.py
    - src/mlProject/utils/common.py
    params:
    - config/config.yaml:
      - data_ingestion.local_data_file
      - data_ingestion.root_dir
      - data_ingestion.source_URL
      - data_ingestion.unzip_dir
    outs:
    - artifacts/data_ingestion/data.zip
    - artifacts/data_ingestion/winequality-red.csv
  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
    - artifacts/data_ingestion/winequality-red.csv
    - src/mlProject/components/data_validation.py
    - src/mlProject/pipeline/stage_02_data_validation.py
    params:
    - config/config.yaml:
      - data_validation.STATUS_FILE
      - data_validation.root_dir
      - data_validation.unzip_data_dir
    - schema.yaml:
      - COLUMNS
    outs:
    - artifacts/data_validation/status.txt
  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
    - artifacts/data_ingestion/winequality-red.csv
    - src/mlProject/components/data_transformation.py
    - src/mlProject/pipeline/stage_03_data_transformation.py
    - artifacts/data_validation/status.txt
    params:
    - config/config.yaml:
      - data_transformation.root_dir
      - data_transformation.data_path
    outs:
    - artifacts/data_transformation/test.csv
    - artifacts/data_transformation/train.csv
  model_trainer:
    cmd: python src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
    - artifacts/data_transformation/train.csv
    - src/mlProject/components/model_trainer.py
    - src/mlProject/pipeline/stage_04_model_trainer.py
    params:
    - config/config.yaml:
      - model_trainer.model_name
      - model_trainer.root_dir
      - model_trainer.test_data_path
      - model_trainer.train_data_path
    - params.yaml:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    - schema.yaml:
      - TARGET_COLUMN
    outs:
    - artifacts/model_trainer/model.joblib
  model_evaluation:
    cmd: python src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
    - artifacts/data_transformation/test.csv
    - artifacts/model_trainer/model.joblib
    - src/mlProject/components/model_evaluation.py
    - src/mlProject/pipeline/stage_05_model_evaluation.py
    params:
    - config/config.yaml:
      - model_evaluation.metric_file_name
      - model_evaluation.model_path
      - model_evaluation.root_dir
      - model_evaluation.test_data_path
    - params.yaml:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    - schema.yaml:
      - TARGET_COLUMN
    metrics:
    - artifacts/model_evaluation/metrics.json:
        cache: false