stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
    - src/mlProject/pipeline/stage_01_data_ingestion.py
    - src/mlProject/components/data_ingestion.py
    - src/mlProject/config/configuration.py
    - src/mlProject/entity/config_entity.py
    - src/mlProject/utils/common.py
    params:
    - config/config.yaml:
      - data_ingestion.local_data_file
      - data_ingestion.root_dir
      - data_ingestion.source_URL
      - data_ingestion.unzip_dir
    outs:
    - artifacts/data_ingestion/data.zip
    - artifacts/data_ingestion/winequality-red.csv
  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
    - artifacts/data_ingestion/winequality-red.csv
    - src/mlProject/components/data_validation.py
    - src/mlProject/pipeline/stage_02_data_validation.py
    params:
    - config/config.yaml:
      - data_validation.STATUS_FILE
      - data_validation.root_dir
      - data_validation.unzip_data_dir
    - schema.yaml:
      - COLUMNS
    outs:
    - artifacts/data_validation/status.txt